services:
  cassandra:
    image: cassandra:4.1
    container_name: cass1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: tp2-cluster
      CASSANDRA_DC: dc1
      CASSANDRA_RACK: rack1
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data: